/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "urlkdytzseervqysilby"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybGtkeXR6c2VlcnZxeXNpbGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMTYzODEsImV4cCI6MjA3NDg5MjM4MX0.TgC-tCsI4LNByhQSa3QJRoG_IyCxjXMdE-Iq4HSEzFU"